#!/usr/bin/env python3
"""regenerate LIB_MAP and BIN_MAP tables from live system + Contents index
   output goes to stdout, pipe it into host_detect.py or whatever"""

import sys, os, re, subprocess, json, gzip, lzma
from urllib.request import urlopen, Request
from collections import OrderedDict

def _fetch(url):
    try:
        req = Request(url, headers={"User-Agent": "Tanuki/0.2.0"})
        with urlopen(req, timeout=30) as r:
            data = r.read()
        if url.endswith(".gz"):
            return gzip.decompress(data).decode("utf-8", errors="replace")
        elif url.endswith(".xz"):
            return lzma.decompress(data).decode("utf-8", errors="replace")
        return data.decode("utf-8", errors="replace")
    except Exception as e:
        print(f"!! fetch failed: {url} -> {e}", file=sys.stderr)
        return None

def _get_ldconfig_map():
    m = {}
    ldconfig = None
    for candidate in ["ldconfig", "/sbin/ldconfig", "/usr/sbin/ldconfig"]:
        if candidate == "ldconfig" or os.path.isfile(candidate):
            ldconfig = candidate
            break
    if not ldconfig:
        print("!! ldconfig not found", file=sys.stderr)
        return m
    try:
        p = subprocess.run([ldconfig, "-p"], capture_output=True, text=True, timeout=30)
        if p.returncode == 0:
            for line in p.stdout.splitlines():
                x = re.match(r"^\s*(\S+)\s+\(([^)]*)\)\s*=>\s*(\S+)", line)
                if x:
                    pkg = x.group(2).split(",")[0].strip()
                    m[x.group(1)] = pkg
    except Exception as e:
        print(f"!! ldconfig -p failed: {e}", file=sys.stderr)
    return m

def _parse_contents(text, arch):
    """parse Contents-arch file, return {soname: pkgname}"""
    m = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("!"):
            continue
        parts = line.split(None, 1)
        if len(parts) < 2:
            continue
        fpath, rest = parts
        if not fpath.startswith("lib/") and not fpath.startswith("usr/lib/"):
            continue
        base = fpath.rsplit("/", 1)[-1]
        if not base.startswith("lib") or ".so" not in base:
            continue
        pkg = rest.split(",")[0].strip().rstrip(",")
        if base and pkg and base not in m:
            m[base] = pkg
    return m

def _get_installed_pkgs():
    """try to figure out what pkg each bin belongs to using dpkg/rpm/pacman -Qo"""
    m = {}
    # try dpkg first
    try:
        p = subprocess.run(["dpkg-query", "-W", "-f", "${Package}\n"], capture_output=True, text=True, timeout=30)
        if p.returncode == 0:
            return m  # we're on debian, no need for mapping
    except: pass
    # try pacman - try to query files
    try:
        p = subprocess.run(["pacman", "-Q", "-o", "/usr/bin/bash"], capture_output=True, text=True, timeout=10)
        if p.returncode == 0:
            # arch - we can try to map from the filesystem
            pass
    except: pass
    return m

def _scan_bins():
    """scan common bin dirs, try to figure out what debian pkg they'd belong to"""
    common_bins = [
        "/usr/bin", "/usr/local/bin", "/bin", "/usr/sbin", "/sbin"
    ]
    # this is rough - just returns a set of bin names
    bins = set()
    for d in common_bins:
        if os.path.isdir(d):
            try:
                for f in os.listdir(d):
                    fp = os.path.join(d, f)
                    if os.path.isfile(fp) and os.access(fp, os.X_OK):
                        bins.add(f)
            except: pass
    return bins

def main():
    print("# generated by generate_lib_map.py")
    print("# run this on a debian/ubuntu system for best results")
    print("")
    print()
    print("LIB_MAP = {")

    ld = _get_ldconfig_map()

    # try to fetch Contents from debian mirror for more soname mappings
    arch = "amd64"
    for a in ["amd64", "arm64", "i386"]:
        u = f"https://deb.debian.org/debian/dists/stable/main/Contents-{a}.gz"
        txt = _fetch(u)
        if txt:
            arch = a
            break

    contents_map = {}
    if txt:
        contents_map = _parse_contents(txt, arch)
        print(f"# fetched Contents-{arch} from debian, got {len(contents_map)} so names", file=sys.stderr)

    # merge ldconfig + contents, ldconfig wins
    merged = dict(contents_map)
    merged.update(ld)
    # also add some common ones that are always needed
    merged["libc.so.6"] = "libc6"
    merged["libm.so.6"] = "libc6"
    merged["ld-linux-x86-64.so.2"] = "libc6"
    merged["ld-linux-aarch64.so.1"] = "libc6"
    merged["libpthread.so.0"] = "libc6"
    merged["libdl.so.2"] = "libc6"
    merged["librt.so.1"] = "libc6"
    merged["libz.so.1"] = "zlib1g"
    merged["libstdc++.so.6"] = "libstdc++6"
    merged["libgcc_s.so.1"] = "libgcc-s1"

    for soname in sorted(merged.keys()):
        pkg = merged[soname]
        print(f'    "{soname}": "{pkg}",')

    print("}")
    print()
    print()
    print("BIN_MAP = {")
    # bin map is hard to auto-generate, so we just output the existing ones
    # plus any we can detect
    print('    "bash": "bash",')
    print('    "sh": "dash",')
    print('    "python3": "python3",')
    print('    "python": "python3",')
    print('    "perl": "perl",')
    print('    "git": "git",')
    print('    "curl": "curl",')
    print('    "wget": "wget",')
    print('    "tar": "tar",')
    print('    "gzip": "gzip",')
    print('    "xz": "xz-utils",')
    print('    "zstd": "zstd",')
    print('    "grep": "grep",')
    print('    "sed": "sed",')
    print('    "awk": "gawk",')
    print('    "vim": "vim",')
    print('    "nvim": "neovim",')
    print('    "less": "less",')
    print('    "sudo": "sudo",')
    print('    "systemctl": "systemd",')
    print('    "journalctl": "systemd",')
    print('    "ip": "iproute2",')
    print('    "ss": "iproute2",')
    print('    "ping": "iputils-ping",')
    print('    "mount": "mount",')
    print('    "umount": "mount",')
    print('    "ps": "procps",')
    print('    "top": "procps",')
    print('    "free": "procps",')
    print('    "pacman": "pacman",')
    print('    "apt": "apt",')
    print('    "dpkg": "dpkg",')

    bins = _scan_bins()
    # add any common ones we detected
    extra_bins = {
        "zsh": "zsh", "fish": "fish", "dash": "dash",
        "make": "make", "cmake": "cmake", "meson": "meson",
        "ninja": "ninja-build", "pkg-config": "pkg-config",
        "gcc": "gcc", "clang": "clang", "ld": "binutils",
        "as": "binutils", "ar": "binutils", "nm": "binutils",
        "objdump": "binutils", "strip": "binutils",
        "patch": "patch", "rsync": "rsync",
        "ssh": "openssh-client", "scp": "openssh-client",
        "htop": "htop", "btop": "btop", "lsof": "lsof",
        "fdisk": "fdisk", "lsblk": "util-linux",
        "blkid": "util-linux", "dmesg": "util-linux",
        "find": "findutils", "xargs": "findutils", "locate": "findutils",
        "unzip": "unzip", "zip": "zip", "bzip2": "bzip2",
        "screen": "screen", "tmux": "tmux",
    }
    for b, p in extra_bins.items():
        if b in bins:
            print(f'    "{b}": "{p}",')

    print("}")
    print()

if __name__ == "__main__":
    main()
